# Generated by Django 6.1.1 on 2026-09-24 10:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('barbershop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField()),
                ('end_time', models.DateTimeField(help_text='Calculated as date_time + service.duration_minutes')),
                ('status', models.CharField(choices=[('PENDING_PAYMENT', 'Pending Payment'), ('CONFIRMED', 'Confirmed'), ('CANCELED', 'Canceled'), ('COMPLETED', 'Completed'), ('NO_SHOW', 'No Show'), ('CANCELED_WITH_PENALTY', 'Canceled with Penalty'), ('REFUNDED', 'Refunded')], default='PENDING_PAYMENT', max_length=30)),
                ('payment_type', models.CharField(choices=[('SUBSCRIPTION', 'Subscription'), ('SINGLE_PERCENTAGE', 'Single Percentage')], max_length=30)),
                ('cancellation_reason', models.TextField(blank=True, null=True)),
                ('canceled_by', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('barber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='barbershop.barber')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='accounts.customerprofile')),
                ('service', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments', to='barbershop.service')),
            ],
        ),
    ]
